### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by philpott** [SirDataFR/gtm_template_consent_mode#1]
https://github.com/SirDataFR/gtm_template_consent_mode/blob/0fa4639fe40b31f699a75c527cc61143f9bc65f3/template.tpl#L1601-L1606

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by nouchy** [comment]
Hello @philpott, thank you for your review. The values used for these parameters are generated by Sirdata and do not need to be URL-encoded. However, you are right, it's a good practice, so we are updating the module.
