### ISSUE TITLE
Blocking issue: Include wait_for_update on the setDefaultConsent Call

### ISSUE THREAD

**Issue by philpott** [SirDataFR/gtm_template_consent_mode#2]
https://github.com/SirDataFR/gtm_template_consent_mode/blob/0fa4639fe40b31f699a75c527cc61143f9bc65f3/template.tpl#L1557C3-L1559C4

When reviewing your template we've noticed that the setDefaultConsentState call does not include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option. This is required for any asynchronous consent management script load to delay tag execution.

You should set a default wait_for_update (say 500) and allow users to override that. Without it present this will cause things to not work as expected.

**Comment by nouchy** [comment]
Hi @philpott, it does include the wait-for-update parameter. As you can see, this field is part of the settings and it is a mandatory field:

![image](https://github.com/SirDataFR/gtm_template_consent_mode/assets/33549554/19e3674b-6383-4b24-8873-58deba19ec97)

The value has to be a positive integer and in such a case the setDefaultConsentState call does include the [wait_for_update](https://developers.google.com/tag-platform/tag-manager/templates/api#setdefaultconsentstate) option.

![image](https://github.com/SirDataFR/gtm_template_consent_mode/assets/33549554/e5aaf27f-420a-4d6a-a6e5-039dbf9d41bf)

But indeed we offer publishers who require synchronous behavior for any reason to disable this parameter by setting the "0" value.

**Comment by philpott** [comment]
I have approved the template

Ah, I missed that one was looking at the code where if they set the value down to 0 it'll skip the parameter only which is still an edge case that isn't ideal -- with async loads its best to always ensure a value is set -- but due to the defaults I'm betting most people don't change that.
